# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52fdad9c6aec7c78673284b878f9bcee00513c6976949fbad7ff0b1e15c57687ecd9a4e1b571b8b852c848940c77da104078f2f9098b3653455fdd176b8a81c6

test:
  secret_key_base: edc890c0ed44e0d5c6a3ef6d2a83d492737f681b084a55f28bec6340dbabecbfd8b37a7eece43d7ff9928ddffa5876d9036d077c43053c262b13fdc451237d8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
